app = 'keycloak-service-np'
primary_region = 'atl'

[build]
  dockerfile = 'Dockerfile'

[env]
  KC_HTTP_ENABLED = 'true'
  KC_HTTP_PORT = '8080'
  KC_PROXY_HEADERS = 'xforwarded'
  KC_HOSTNAME = 'keycloak-service-np.fly.dev'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
