version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-local
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]
