version: '3.8'
services:
  keycloak-service-db:
    image: postgres:16
    container_name: keycloak-service-db
    environment:
      POSTGRES_DB: keycloak_dev
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - beaver-network

  keycloak-service:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    image: keycloak-service:dev
    container_name: keycloak-service
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-service-db:5432/keycloak_dev
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "127.0.0.1:8090:8080"
    command: ["start-dev", "--import-realm"]
    depends_on:
      - keycloak-service-db
    networks:
      - beaver-network

volumes:
  keycloak_db_data:

networks:
  beaver-network:
    external: true