# fly.toml app configuration file generated for keycloak-service-np on 2025-08-21T17:50:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'keycloak-service-np'
primary_region = 'atl'

[build]

[env]
  KC_HOSTNAME = "https://keycloak-service-np.fly.dev"
  KC_HOSTNAME_ADMIN = "https://keycloak-service-np.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
